application/Website/config/routes.rb
Rails.application.routes.draw do
  apipie
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  get 'welcome/index'

   root 'welcome#index'

  resources :trainings

end

application/Website/app/models/training.rb
class Training < ActiveRecord::Base
  validates :title, presence:true,
                    length: { minimum: 5 }
end

application/Website/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

application/Website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

application/Website/app/controllers/trainings_controller.rb
# Class with all trainings methods
class TrainingsController < ApplicationController

before_action :authenticate_user!

# Define new training
def new
@training = Training.new
end

# Create new training
def create
@training = Training.new(training_params)
if @training.save
redirect_to @training
else
render 'new'
end
#render plain: params[:training].inspect
end

# Show training by id
# * *Args*    :
  # - +id+ -> the id of training
def show
@training = Training.find(params[:id])
end

# Show all trainings
def index
@trainings = Training.all
end

# Edit training by id:
# * *Args*    :
  # - +id+ -> the id of training
def edit
@training = Training.find(params[:id])
end

# Update training
# * *Args*    :
  # - +id+ -> the id of training
def update
@training = Training.find(params[:id])

if @training.update(training_params)
redirect_to @training
else
render 'edit'
end
end
# Delete training in database
# * *Args*    :
  # - +id+ -> the id of training
def destroy
@training = Training.find(params[:id])
@training.destroy

redirect_to trainings_path
end

private
def training_params
params.require(:training).permit(:title, :text)
end

end

application/Website/app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  GET /resource/confirmation/new
  def new
    super
  end

  POST /resource/confirmation
  def create
    super
  end

  GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

application/Website/app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

application/Website/app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  GET /resource/password/new
  def new
    super
  end

  POST /resource/password
  def create
    super
  end

  GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

application/Website/app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  GET /resource/sign_up
  def new
    super
  end

  POST /resource
  def create
    super
  end

  GET /resource/edit
  def edit
    super
  end

  PUT /resource
  def update
    super
  end

  DELETE /resource
  def destroy
    super
  end

  GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

application/Website/app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
 before_filter :configure_sign_in_params, only: [:create]

  GET /resource/sign_in
  def new
    super
  end

  POST /resource/sign_in
  def create
    super
  end

  DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

application/Website/app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  GET /resource/unlock/new
  def new
    super
  end

  POST /resource/unlock
  def create
    super
  end

  GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

application/Website/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

application/Website/app/helpers/application_helper.rb
module ApplicationHelper
end

application/Website/app/helpers/trainigs_helper.rb
module TrainigsHelper
end

application/Website/app/helpers/trainings_helper.rb
module TrainingsHelper
end

application/Website/app/helpers/welcome_helper.rb
module WelcomeHelper
end

application/Website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Website</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <!-- header -->
  <div id="home" class="header">
    <!-- container -->
    <div class="container">
      <div class="header-top">
        <div class="header-logo">
          <h1><%= link_to 'FitActivity', root_path %></h1>
        </div>
        <div class="top-nav">
          <span class="menu"><%= image_tag("menu.png") %></span>
          <ul class="nav1">
            <li><%= link_to 'Home', root_path %>
            </li>
            <li><%= link_to 'Trainings', trainings_path, class: "scroll" %>
            </li>
          <%= render 'devise/menu/login_items' %>
          <%= render 'devise/menu/registration_items' %>
          </ul>
        </div>
        <div class="clearfix"> </div>
      </div>
    </div>
  </div>
  <!-- container -->




  <% if flash[:notice] %>
   <p class="notice">    <%=notice %>  </p>
  <% end %>

<% if flash[:alert] %>
  <p class="alert">    <%=alert %>  </p>
<% end %>

<!-- dynamic data -->
  <%= yield %>
<!-- end of dynamic data -->

  <!-- icons -->
  <div class="footer">
    <div class="icons">
      <!-- container -->
      <div class="container">
        <ul class="wow bounceIn" data-wow-delay="0.4s">
          <li>
            <span class="light"> </span>
          </li>
          <li>
            <span class="glob"> </span>
          </li>
          <li>
            <span class="camra"> </span>
          </li>
          <li>
            <span class="setting"> </span>
          </li>
          <li>
            <span class="mike"> </span>
          </li>
          <li>
            <span class="money"> </span>
          </li>
        </ul>
      </div>
      <!-- container -->
    </div>
    <!-- icons -->
</div>
</body>

</html>

application/Website/app/views/trainings/_form.html.erb
<%= form_for @training do |f| %>
<% if @training.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@training.errors.count, "error") %> prohibited
    this training from being saved:</h2>
    <ul>
      <% @training.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  <% end %>

application/Website/app/views/trainings/edit.html.erb
<div class="trening-info">
<h2>Edit training</h2>
</div>
<%= render 'form' %>
<div class="trening-info-nav">
<%= link_to 'Back', trainings_path, :class=>"nice_button" %>
</div>

application/Website/app/views/trainings/index.html.erb
<div class="services">
  <div class="container">
    <div class="works-hedding">
      <h3>List of trainings</h3>
      <%= link_to 'New training', new_training_path, :class=>"nice_button" %></li>
    <div class="clearfix"></div>
    <!-- <table>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th colspan="2"></th>
      </tr>

      <% @trainings.each do |training| %>
      <tr>
        <td><%= training.title %></td>
        <td><%= training.text %></td>
        <td><%= link_to 'Show', training_path(training) %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training_path(training),
        method: :delete, data: { confirm: 'Czy jestes pewny?' } %></td>
      </tr>
      <% end %>
    </table> -->
  </div>
  <div id="portfoliolist">

    <% @trainings.each do |training| %>
    <div class="portfolio card mix_all" style="display:inline-block; opacity:1;" data-cat="card">

      <div class="portfolio-wrapper">
        <div class="b-link-stripe" href="#">
          <div class="b-wrapper">
            <a href="<%= training_path(training) %>">
              <h2 class="b-animate-b-from-left"><%= training.title %></h2>
              <p class="b-animate-b-from-left"><%= training.text %></p><br/>
            </a>
            <p class="b-animaate-b-from-left">
              <%= link_to 'Edit', edit_training_path(training) %>
              <%= link_to 'Destroy', training_path(training),    method: :delete, data: { confirm: 'Czy jestes pewny?' } %></p>
          </div>
        </div>

      </div>

    </div>
    <% end %>
  </div>
</div>
</div>

application/Website/app/views/trainings/new.html.erb
<div class="trening-info">
<h2>New Training</h2>
</div>
<%= render 'form' %>
<div class="trening-info-nav">
<%= link_to 'Back', trainings_path, :class=>"nice_button" %>
</div>

application/Website/app/views/trainings/show.html.erb
<div class="trening-info">
  <h2>
  <%= @training.title %>
</h2>

<h3>
  <%= @training.text %>
</h3>
</div>

<div class="trening-info-nav">
<%= link_to 'Back', trainings_path, :class=>"nice_button" %>
<%= link_to 'Edit', edit_training_path(@training), :class=>"nice_button" %>
</div>

application/Website/app/views/welcome/index.html.erb
<div class="banner">
  <div class="banner-img">
    <div class="container">
      <div class="banner-info ">
        <a class="play-icon">
          <span></span>
        </a>
        <div class="banner-text">
          <h2>Your personal trainer</h2>
          <span class="btn btn-primary">
            <i class="glyphicon glyphicon-user"></i>
            Register now
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="col-md-4">
    <h3>
      Text heading 1
    </h3>
    <span>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas consectetur consequat mi quis bibendum. Suspendisse potenti. Quisque nec arcu feugiat, ultricies neque sit amet, sagittis lectus. Curabitur a euismod arcu. Proin finibus volutpat
      massa, sed laoreet elit eleifend eu.
    </span>
  </div>
  <div class="col-md-4">
    <h3>
      Text heading 1
    </h3>
    <span>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas consectetur consequat mi quis bibendum. Suspendisse potenti. Quisque nec arcu feugiat, ultricies neque sit amet, sagittis lectus. Curabitur a euismod arcu. Proin finibus volutpat
      massa, sed laoreet elit eleifend eu.
    </span>
  </div>
  <div class="col-md-4">
    <h3>
      Text heading 1
    </h3>
    <span>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas consectetur consequat mi quis bibendum. Suspendisse potenti. Quisque nec arcu feugiat, ultricies neque sit amet, sagittis lectus. Curabitur a euismod arcu. Proin finibus volutpat
      massa, sed laoreet elit eleifend eu.
    </span>
  </div>
</div>